spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: provider-admin
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
server:
  port: 10000