spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: addons-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: http://192.168.247.142/zzp/spring-cloud-netflix.git
          search-paths: repo
          username: zzp
          password: 12345678

server:
  port: 8888

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/